import { jsPDF } from 'jspdf';
import { type AgentMessage } from '../mockData';

export const generatePDFReport = (idea: string, messages: AgentMessage[]) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    let yPos = 20;

    // Title
    doc.setFontSize(22);
    doc.setTextColor(59, 130, 246); // Blue-500
    doc.text("Startup Feasibility Report", margin, yPos);
    yPos += 15;

    // Idea Section
    doc.setFontSize(12);
    doc.setTextColor(100);
    doc.text("Evaluated Idea:", margin, yPos);
    yPos += 7;
    doc.setFontSize(14);
    doc.setTextColor(0);
    const splitIdea = doc.splitTextToSize(idea, pageWidth - 2 * margin);
    doc.text(splitIdea, margin, yPos);
    yPos += splitIdea.length * 7 + 10;

    // Line Separator
    doc.setDrawColor(200);
    doc.line(margin, yPos, pageWidth - margin, yPos);
    yPos += 15;

    // Agent Findings
    doc.setFontSize(16);
    doc.setTextColor(0);
    doc.text("Agent Analysis", margin, yPos);
    yPos += 10;

    messages.forEach((msg) => {
        // Check for page break
        if (yPos > 270) {
            doc.addPage();
            yPos = 20;
        }

        // Agent Name
        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');

        if (msg.agent === 'Researcher') doc.setTextColor(59, 130, 246); // Blue
        else if (msg.agent === 'Critic') doc.setTextColor(239, 68, 68); // Red
        else if (msg.agent === 'Planner') doc.setTextColor(16, 185, 129); // Emerald

        doc.text(msg.agent.toUpperCase(), margin, yPos);

        // Message Type Badge (Text representation)
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        doc.setTextColor(150);
        const typeText = `[${msg.type.toUpperCase()}]`;
        doc.text(typeText, margin + 35, yPos); // Offset agent name

        yPos += 6;

        // Content
        doc.setFontSize(10);
        doc.setTextColor(50);
        const splitContent = doc.splitTextToSize(msg.content, pageWidth - 2 * margin);
        doc.text(splitContent, margin, yPos);

        yPos += splitContent.length * 5 + 8;
    });

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(
            `Generated by Startup Validator AI - Page ${i} of ${pageCount}`,
            pageWidth / 2,
            290,
            { align: 'center' }
        );
    }

    doc.save(`${idea.replace(/\s+/g, '_').substring(0, 20)}_Report.pdf`);
};
